version: 2

sources:
  - name: raw_qwt
    database: "{{env_var('DBT_QWTDB', 'QWT_ANALYTICS_DEV')}}"
    schema: "{{env_var('DBT_RAWSCHEMA', 'RAW_DEV')}}"
    tables:
      - name: raw_customer
      - name: raw_products
      - name: raw_orders
      - name: raw_orderdetails
      - name: raw_employees
      - name: raw_empoffice
      - name: raw_shipments
      - name: raw_suppliers
      - name: raw_offices