version: 2
 
seeds:
  - name: lkp_division
    config:
      schema: "{{env_var('DBT_LOOKUPSCHEMA', 'LOOKUP_DEV')}}"

  - name: lkp_configuration
    config:
      schema: "{{env_var('DBT_LOOKUPSCHEMA', 'LOOKUP_DEV')}}"    

  - name: lkp_shipments
    config:
      schema: "{{env_var('DBT_LOOKUPSCHEMA', 'LOOKUP_DEV')}}"      